### ISSUE TITLE
Apparently stopped working

### ISSUE THREAD

**Issue by aaronhowser1** [dylanpdx/vxReddit#2]
![image](https://github.com/dylanpdx/vxReddit/assets/15698722/919abc35-4737-4b9e-86ae-6dde1b1c004a)
![image](https://github.com/dylanpdx/vxReddit/assets/15698722/51d73c15-59b4-43a5-9f8f-f384082ab9b3)

https://www.vxreddit.com/r/Palworld/comments/1aeinxj/how_to_transfer_any_weight_resources_without/
https://www.vxreddit.com/r/196/comments/1aezxfh/feedback_loop_rule/

**Comment by dylanpdx** [comment]
Looking into it

**Comment by Irru-** [comment]
Is 'they' Discord in this case? If that's so, is it fully out of your control? I'd hate to see this amazing stuff go

**Comment by dylanpdx** [comment]
Yes, it's discord's issue from what I gather. I'd love to be wrong though, but from what I understand they're trying to convert or process the video somehow and it isn't working. vxReddit embeds still work correctly on Telegram

**Comment by LofiTurtle** [comment]
Tested today and embeds are working for me in discord now, so it seems like they fixed their issue

**Comment by dylanpdx** [comment]
Whoops, forgot to close. Yes, this is fixed

**Comment by aaronhowser1** [comment]
![image](https://github.com/dylanpdx/vxReddit/assets/15698722/5a005d4b-51cb-46f4-a457-0b22168b14cf)
<https://www.vxreddit.com/r/modernwarfare/comments/i8zlgy/breach_and_clear/>

**Comment by aaronhowser1** [comment]
This is from yesterday

**Comment by fadster** [comment]
Sorry but it's not working.
