### ISSUE TITLE
Videos not playing in embed

### ISSUE THREAD

**Issue by Dave247** [dylanpdx/vxReddit#5]
I think this is the same as #3, except that it appears to affect both Telegram and Discord. I guess Reddit must have changed something with their API yet again.

**Screenshots:**

<details>
<summary>Discord Desktop</summary>
<img src="https://github.com/user-attachments/assets/14d3d06f-4888-4c7c-8198-57966be1f46b">
</details>

<details>
<summary>Discord Mobile</summary>
<img src="https://github.com/user-attachments/assets/f2600b34-f060-4950-9445-e537db484f54">
</details>

<details>
<summary>Telegram Desktop</summary>
<img src="https://github.com/user-attachments/assets/2bb4754b-40e2-49d6-8b40-96e353436567">
</details>

<details>
<summary>Telegram Mobile</summary>
<img src="https://github.com/user-attachments/assets/577272f5-6dd5-45a6-a753-6e6ee62cf832">
</details>

**Comment by dylanpdx** [comment]
Thanks for the detailed bug report! I'll take a look at this when I can.
Leaving the URL for the post here for my future reference: https://www.vxreddit.com/r/NatureIsFuckingLit/comments/df9v0k/

**Comment by Dave247** [comment]
> Thanks for the detailed bug report! I'll take a look at this when I can.
> Leaving the URL for the post here for my future reference: https://www.vxreddit.com/r/NatureIsFuckingLit/comments/df9v0k/

Ah I forgot the most important thing, the URL to the example I was showing.😅

**Comment by dylanpdx** [comment]
This should be fixed now! It might take a while for embed caches to update, but posts that had this issue will hopefully embed correctly now.
![image](https://github.com/user-attachments/assets/4b20886e-44fb-401b-90a8-f81aa9cec06c)

**Comment by Dave247** [comment]
Looks great! Thanks for finding the time to fix it so quickly, and thanks for taking the time to make this in the first place.
